### ISSUE TITLE
Отделить разметку

### ISSUE THREAD

**Issue by alexey-pd** [MityaDV/automation_gulp#3]
Удобнее когда каждый блок лежит в своей папке
`blocks/header`

внутри файл стилей, скриптов, разметки
```
header.js
header.scss
header.html
```

подключается через `@include` 
https://www.npmjs.com/package/gulp-file-include

чтобы не редактировать разметку данные могут приходить параметрами с проверкой условий
https://www.npmjs.com/package/gulp-file-include#if-statement

карточки в цикле можно выводить через `@loop`
https://www.npmjs.com/package/gulp-file-include#loop-statement

это позволяет свободно перемещать блоки между страницами 

без возможности забыть часть кода при обновлении блоков

**Comment by MityaDV** [comment]
Спасибо, нужно попробовать))

**Comment by MityaDV** [comment]
А такая практика по разделению всего кода на более мелкие сегменты, сейчас практикуется? Опыта применения такого нет, поэтому спрашиваю для себя интересно, сейчас углублюсь почитаю и попробую.

**Comment by MityaDV** [comment]
Сейчас работаю над портфолио своим, как раз можно попробовать)

**Comment by alexey-pd** [comment]
компонентный подход применяется широко - дублировать плохой паттерн

**Comment by MityaDV** [comment]
Разобравшись и применив всё выше описанное я смогу свою автоматизацию вместо портфолио показывать))

**Comment by MityaDV** [comment]
Да, ты умеешь подкинуть тем для повышения квалификации)) Спасибо огромное, прям руки зачесались попробовать))

**Comment by alexey-pd** [comment]
Главное навык "дойти до проекта" приобрести, сборки всегда весело настраивать :upside_down_face: портфолио важнее
